name: Deploy Front

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  

      - name: Install dependencies and build
        run: |
          cd front-end
          npm install
          npm run build

      - name: Deploy via SSH
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          hostname: 34.163.193.237
          username: noa_pozzodiborgo
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/noapo/cooking-booking/
            git pull

